apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deploy
  labels:
    app: demo-voting-app
    name: redis-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: redis-app-pod
      labels:
        name: redis-app-pod
        app: demo-voting-app
    spec:
      containers:
      - image: redis
        name: redis-app
        ports:
        - containerPort: 6379