apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  selector:
    app: demo-voting-app
    name: redis-app-pod
  type: ClusterIP
  ports:
  - targetPort: 6379
    port: 6379