apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  selector:
    app: demo-voting-app
    name: result-app-pod
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30005